#!/usr/bin/env bash
#              bash 4.3.11(1)   Linux 3.13.0 Ubuntu 14.04.3   Date : 2016-03-08
#
# _______________|  bin2music : binary bits to music.
#
#           Usage:  $ bin2music [file=/dev/urandom]
#
#        Examples:  $ ./bin2music                  # Random music in minor key!
#                   $ ./bin2music foo.jpg          # Musically play an image.
#                   $ cat foo.jpg | ./bin2music -  # Pipe works also.
#
#    Dependencies:  sox (but aplay can be substituted, see playback function)
#
#  CHANGE LOG  Repository: https://github.com/rsvp/randomsys 
#  2016-03-08  Add less treble and bass, with more tremelo, as sound effects.
#                 Reverb with sox does not work well here.
#  2016-03-06  Convert from one-liner to multi-line for clarity
#                 and modification: any binary file can be played,
#                 replace aplay by sox in playback function.
#  2016-03-05  Add converted source from 2016-03-04 blog post by:
#                 Robert Elder, robert@robertelder.org
#                 http://blog.robertelder.org/bash-one-liner-compose-music
#                 His extensive comments preserved at EOF.


#           _____ PREAMBLE_v3: settings, variables, and error handling.
#
LC_ALL=POSIX
#      locale means "ASCII, US English, no special rules, 
#      output per ISO and RFC standards." 
#      Esp. use ASCII encoding for glob and sorting characters. 
shopt -s   extglob
#     ^set extended glob for pattern matching.
shopt -s   failglob
#         ^failed pattern matching signals error.
set -e
#   ^errors checked: immediate exit if a command has non-zero status. 
set -o pipefail
#   ^exit status on fail within pipe, not (default) last command.
set -u
#   ^unassigned variables shall be errors.
#    Example of default VARIABLE ASSIGNMENT:  arg1=${1:-'foo'}

file=${1:-'/dev/urandom'}

program=${0##*/}   #  similar to using basename
errf=$( mktemp /dev/shm/88_${program}_tmp.XXXXXXXXXX )


cleanup () {
     #  Delete temporary files, then optionally exit given status.
     local status=${1:-'0'}
     rm -f $errf
     [ $status = '-1' ] ||  exit $status      #  thus -1 prevents exit.
} #--------------------------------------------------------------------
warn () {
     #  Message with basename to stderr.          Usage: warn "message"
     echo -e "\n !!  ${program}: $1 "  >&2
} #--------------------------------------------------------------------
die () {
     #  Exit with status of most recent command or custom status, after
     #  cleanup and warn.      Usage: command || die "message" [status]
     local status=${2:-"$?"}
     cat $errf >&2
     cleanup -1  &&   warn "$1"  &&  exit $status
} #--------------------------------------------------------------------
trap "die 'SIG disruption, but cleanup finished.' 114" 1 2 3 15
#    Cleanup after INTERRUPT: 1=SIGHUP, 2=SIGINT, 3=SIGQUIT, 15=SIGTERM
trap "die 'unhandled ERR via trap, but cleanup finished.' 116" ERR
#    Cleanup after command failure unless it's part of a test clause.
#
# _______________     ::  BEGIN  Script ::::::::::::::::::::::::::::::::::::::::


tones () {
     #            "0,2,4,5,7,9,11,12" for major, instead of minor:
     awk '{ split("0,2,3,5,7,8,10,12", a,",");    \
              for (i = 0; i < 1; i+= 0.0001)      \
              printf("%08X\n", 100*sin(1382*exp((a[$1 % 8]/12)*log(2))*i)) }'
}


playback () {
     ##       Various playback options:
     #  aplay -c 2 -f S32_LE -r 16000  #  As originally proposed.
     #        For macs, sox seems better:
     #  sox -t raw -r 64k -c 1 -e unsigned -b 8 - -d
     sox -t raw -r 64k -c 1 -e unsigned -b 8 - -d treble -27 bass -3 \
         tremolo 0.20 43 
}


cat "$file" | hexdump -v -e '/1 "%u\n"'  \
     | tones                             \
     | xxd -r -p                         \
     | playback


cleanup    #  Instead of: trap arg EXIT
# _______________ EOS ::  END of Script ::::::::::::::::::::::::::::::::::::::::


#  _______________ Bash One-Liner: Compose Music From Entropy in /dev/urandom
#
#  Robert Elder, robert@robertelder.org, Twitter: @RobertElderSoft  
#  http://blog.robertelder.org/bash-one-liner-compose-music
#  March 4, 2016

#  cat /dev/urandom | hexdump -v -e '/1 "%u\n"' | awk '{ split("0,2,4,5,7,9,11,12", a,","); for (i = 0; i < 1; i+= 0.0001) printf("%08X\n", 100*sin(1382*exp((a[$1 % 8]/12)*log(2))*i)) }' | xxd -r -p | aplay -c 2 -f S32_LE -r 16000

#  The above command was tested on Ubuntu 14.04.  You should hear music play
#  through your speakers.
#  
#            _____ cat /dev/urandom
#  
#  prints the contents of /dev/urandom to stdout. Since the [non-blocking] output
#  of /dev/urandom is random binary bytes, we can use hexdump to format it into
#  nice integers from 0-255:
#  
#            _____ hexdump -v -e '/1 "%u\n"'
#  
#  Here is a sample of the output from hexdump:
#  
#       cat /dev/urandom  | hexdump -v -e '/1 "%u\n"' | head
#       135
#       16
#       156
#       54
#       115
#       156
#       116
#       20
#       59
#       191
#  
#  
#  The -v flag gets rid of the hexdump's default behaviour of replacing repeated
#  lines with a '*' character.  The -e flag uses '/1 "%u\n"' to print out the
#  binary byte as an a formatted decimal number.
#  
#  These integers in the range of 0-255 are then passed into awk, one line at a
#  time:
#  
#            _____ awk '...'
#  
#  The ... part is the following small program:
#  
#       split("0,2,4,5,7,9,11,12",a,",");
#       for (i = 0; i < 1; i+= 0.0001) 
#       printf("%08X\n", 100*sin(1382*exp((a[$1 % 8]/12)* log(2))*i))
#  
#  
#  The line: split("0,2,4,5,7,9,11,12",a,",");
#  
#  creates an array 'a' which encodes the relative number of semitones from the
#  base note in a MAJOR musical scale.  This array is useful in the print
#  statement because the frequency in Hertz of a musical note with equal
#  temperament can be calculated using the following formula: 440 * 2^(semitone
#  distance / 12).  440Hz has arbitrarily been chosen as the reference note, and
#  it represents the frequency of A4.
#  
#  [ For MINOR scale use: split("0,2,3,5,7,8,10,12", a,","); ]
#  
#  The for loop then prints formatted 4 byte hexadecimal numbers that represent
#  the amplitude of the sound wave at a given point in time:
#  
#       printf("%08X\n", 100*sin(1382*exp((a[$1 % 8]/12)*log(2))*i))
#  
#  The formula: 100*sin(1382*exp((a[$1 % 8]/12)*log(2))*i)
#  
#  Can be broken down as follows:
#  
#       100 A scalar multiple used to control the volume.
#       *
#       sin(
#               1382 =~ 440 * 3.14159
#               *
#               exp(  Awk doesn't seem to support arbitrary powers, 
#                     so we use 2^x = e^(x *ln(2))
#                       (
#                               a[$1 % 8] Pick semitone randomly on major scale
#                               /
#                               12   Divide by 12 per the formula
#                       )
#                       *
#                       log(2)
#               )
#               *
#               i  The counter in the for loop that counts from 0 to 1
#       )
#  
#  
#  The amount of time that each note is played for can be controlled by changing
#  how fast the for loop counts up to 1.  This number will also affect the
#  perceived frequency.
#  
#  The above formula makes a bit more sense if you think about it in the following
#  way.  If you did
#  
#       for (i = 0; i < 1; i+= 0.0001) sin(i * 3.14159);
#  
#  This will just calculate values on one cycle of a sine curve.  If you then
#  multiply 'i' by a frequency X of a musical note, each iteration of the for
#  loop will calculate points on the X cycles of notes of the given frequency so
#  the amplitude will change faster than the original 1 cycle per completion of
#  the for loop.
#  
#  The next part of the pipe uses xxd to convert the 8 byte hexadecimal values back
#  into binary:
#  
#       xxd -r -p
#  
#  Which is then fed into aplay and turned into audible sound:
#  
#       aplay -c 2 -f S32_LE -r 16000
#  
#  
#  _______________ SAD Music
#  
#  If you want to make the music sound sad, you can change from the major scale to
#  a minor scale:

#  cat /dev/urandom | hexdump -v -e '/1 "%u\n"' | awk '{ split("0,2,3,5,7,8,10,12", a,","); for (i = 0; i < 1; i+= 0.0001) printf("%08X\n", 100*sin(1382*exp((a[$1 % 8]/12)*log(2))*i)) }' | xxd -r -p | aplay -c 2 -f S32_LE -r 16000 


#  vim: set fileencoding=utf-8 ff=unix tw=78 ai syn=sh :
